// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe6TVxdvewnoI4JaJzGlnQ5KLcxlHgAz0',
    appId: '1:1078600878591:web:e73bbc2952b43ca0d97fca',
    messagingSenderId: '1078600878591',
    projectId: 'msgapp-f2647',
    authDomain: 'msgapp-f2647.firebaseapp.com',
    storageBucket: 'msgapp-f2647.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2MqwRRidIZJjHb3pWH_26BG4gBFxKpN8',
    appId: '1:1078600878591:android:0c6ab22583f3972ad97fca',
    messagingSenderId: '1078600878591',
    projectId: 'msgapp-f2647',
    storageBucket: 'msgapp-f2647.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf9cc7ZZQv0PN-_Xx_8Sqh_oYrnSGMlp0',
    appId: '1:1078600878591:ios:b69068c264341bedd97fca',
    messagingSenderId: '1078600878591',
    projectId: 'msgapp-f2647',
    storageBucket: 'msgapp-f2647.firebasestorage.app',
    iosBundleId: 'com.example.msgappFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf9cc7ZZQv0PN-_Xx_8Sqh_oYrnSGMlp0',
    appId: '1:1078600878591:ios:b69068c264341bedd97fca',
    messagingSenderId: '1078600878591',
    projectId: 'msgapp-f2647',
    storageBucket: 'msgapp-f2647.firebasestorage.app',
    iosBundleId: 'com.example.msgappFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe6TVxdvewnoI4JaJzGlnQ5KLcxlHgAz0',
    appId: '1:1078600878591:web:ff3e606b212a85bad97fca',
    messagingSenderId: '1078600878591',
    projectId: 'msgapp-f2647',
    authDomain: 'msgapp-f2647.firebaseapp.com',
    storageBucket: 'msgapp-f2647.firebasestorage.app',
  );
}
